application: betalibtracker 
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  login: required
  auth_fail_action: unauthorized

- url: /public
  static_dir: public

- url: /main
  script: libtracker.py
  login: required
  auth_fail_action: unauthorized

- url: /.*
  script: libtracker.py
  login: required
